services:
  nginx:
    image: nginx:latest
    command: >
      bash -c "echo '<h1>Coolify ✅ شغال تمام</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
