version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app-network
    restart: always

  php:
    image: php:8.2-fpm-alpine
    container_name: php_fpm
    volumes:
      - ./code:/var/www/html
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
