version: "3.9"

services:
  php:
    image: php:8.3-fpm
    restart: always
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
