version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./code:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  php:
    image: php:8.2-fpm
    container_name: php_fpm
    volumes:
      - ./code:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
