version: "3.8"

services:
  app:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    restart: always

  web:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    restart: always
