version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8085:80"          
    volumes:
      - .:/var/www/html  
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.2-fpm
    container_name: php_fpm
    volumes:
      - .:/var/www/html   
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
