version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8085:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx:/etc/nginx/conf.d 
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.2-fpm
    container_name: php_fpm
    volumes:
      - ./code:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
